### ISSUE TITLE
Not working in Ubuntu 23.04, Python 3.11.6 : missing lts.decode()

### ISSUE THREAD

**Issue by jradxl** [getmail6/getmail6#173]
I'm sorry by my Python skills aren't sufficient to understand this.

decode() missing

getmailcore/utilities.py", line 62, in <lambda>
    tostr = lambda lts: lts.decode()

$ getmail -v 
getmail version 6.18.13
Copyright (C) 1998-2023 Charles Cazabon and others. Licensed under GNU GPL version 2.
SimpleIMAPSSLRetriever:UUU@XXXX.co.uk@mail.XXXX.co.uk:993: read_all and not delete -- all messages will be retrieved each time getmail is run
SimpleIMAPSSLRetriever:UUU@XXXX.co.uk@mail.XXXX.co.uk:993:

Exception: please read docs/BUGS and include the following information in any bug report:

  getmail version 6.18.13
  Python version 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]

Unhandled exception follows:
    File "/usr/local/bin/getmail", line 1022, in main
    success = go(configs, options.idle)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/bin/getmail", line 193, in go
    retriever.select_mailbox(mailbox)
    File "/usr/local/lib/python3.11/dist-packages/getmailcore/_retrieverbases.py", line 1498, in select_mailbox
    uidvalidity = tostr(self.conn.response('UIDVALIDITY')[1][0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/dist-packages/getmailcore/utilities.py", line 62, in <lambda>
    tostr = lambda lts: lts.decode()
                        ^^^^^^^^^^
  AttributeError: 'NoneType' object has no attribute 'decode'

Please also include configuration information from running getmail
with your normal options plus "--dump".

getmail -v --dump
getmail version 6.18.13
Copyright (C) 1998-2023 Charles Cazabon and others. Licensed under GNU GPL version 2.
getmail configuration:
  getmail version 6.18.13
  Python version 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
  retriever:  SimpleIMAPSSLRetriever(ca_certs="None", certfile="None", getmaildir="/home/UUU/.getmail", imap_on_delete="None", imap_search="None", keyfile="None", mailboxes="('INBOX',)", move_on_delete="None", password="*", password_command="('/usr/bin/pass', 'Email/UUU@XXXX.co.uk')", port="993", record_mailbox="True", server="mail.XXXX.co.uk", ssl_cert_hostname="None", ssl_ciphers="None", ssl_fingerprints="()", ssl_version="None", timeout="180", use_cram_md5="False", use_kerberos="False", use_peek="True", use_xoauth2="False", username="UUU@XXXX.co.uk")
  destination:  Maildir(filemode="384", path="/home/XXXX/Mail/UUU@XXXX.co.uk/INBOX/", user="None")
  options:
    delete : False
    delete_after : 0
    delete_bigger_than : 0
    delivered_to : True
    fingerprint : False
    logfile : None
    max_bytes_per_session : 0
    max_message_size : 0
    max_messages_per_session : 0
    message_log : None
    message_log_syslog : False
    message_log_verbose : False
    netrc_file : None
    read_all : True
    received : True
    skip_imap_fetch_size : False
    to_oldmail_on_each_mail : False
    use_netrc : False
    verbose : 1

**Comment by jradxl** [comment]
In my ignorance I have changed line to

`uidvalidity = str(self.conn.response('UIDVALIDITY')[1][0])`

**Comment by rpuntaie** [comment]
"changed 1498 line to ...", but that is the line 1498 also in the repo. How did you change that line?
If None can happen I would change it to

``` python
            uidvalidity = tostr(self.conn.response('UIDVALIDITY')[1][0] or b"") or None
```

**Comment by jradxl** [comment]
Hi. I may have misunderstood you question. I git cloned the repository and worked with vscode on my clone to find the issue,
if the original 1498 line is tostr(...) I assumed the result must be a string.

**Comment by rpuntaie** [comment]
Ah. OK. Your change was from `tostr` to `str`.  `tostr` converts to python2 unicode/python3 str from bytes. The original should be bytes. `str(b'xyz') produces b'xyz'. b'xyz'.decode() converts to the `xyz` unicode str.
